// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/rithmic/rithmic.proto

package rithmic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepthRequest) Reset() {
	*x = DepthRequest{}
	mi := &file_proto_rithmic_rithmic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthRequest) ProtoMessage() {}

func (x *DepthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rithmic_rithmic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthRequest.ProtoReflect.Descriptor instead.
func (*DepthRequest) Descriptor() ([]byte, []int) {
	return file_proto_rithmic_rithmic_proto_rawDescGZIP(), []int{0}
}

func (x *DepthRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_proto_rithmic_rithmic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rithmic_rithmic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_proto_rithmic_rithmic_proto_rawDescGZIP(), []int{1}
}

func (x *PriceLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceLevel) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DepthUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeTsNs  int64                  `protobuf:"varint,1,opt,name=exchange_ts_ns,json=exchangeTsNs,proto3" json:"exchange_ts_ns,omitempty"`
	Bids          []*PriceLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*PriceLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepthUpdate) Reset() {
	*x = DepthUpdate{}
	mi := &file_proto_rithmic_rithmic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthUpdate) ProtoMessage() {}

func (x *DepthUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rithmic_rithmic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthUpdate.ProtoReflect.Descriptor instead.
func (*DepthUpdate) Descriptor() ([]byte, []int) {
	return file_proto_rithmic_rithmic_proto_rawDescGZIP(), []int{2}
}

func (x *DepthUpdate) GetExchangeTsNs() int64 {
	if x != nil {
		return x.ExchangeTsNs
	}
	return 0
}

func (x *DepthUpdate) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *DepthUpdate) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

var File_proto_rithmic_rithmic_proto protoreflect.FileDescriptor

const file_proto_rithmic_rithmic_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/rithmic/rithmic.proto\x12\arithmic\"&\n" +
	"\fDepthRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"6\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\x85\x01\n" +
	"\vDepthUpdate\x12$\n" +
	"\x0eexchange_ts_ns\x18\x01 \x01(\x03R\fexchangeTsNs\x12'\n" +
	"\x04bids\x18\x02 \x03(\v2\x13.rithmic.PriceLevelR\x04bids\x12'\n" +
	"\x04asks\x18\x03 \x03(\v2\x13.rithmic.PriceLevelR\x04asks2Q\n" +
	"\x0eRithmicSidecar\x12?\n" +
	"\x0eSubscribeDepth\x12\x15.rithmic.DepthRequest\x1a\x14.rithmic.DepthUpdate0\x01BBZ@github.com/Longfortv5/longfort-v7-briefings/level2/proto/rithmicb\x06proto3"

var (
	file_proto_rithmic_rithmic_proto_rawDescOnce sync.Once
	file_proto_rithmic_rithmic_proto_rawDescData []byte
)

func file_proto_rithmic_rithmic_proto_rawDescGZIP() []byte {
	file_proto_rithmic_rithmic_proto_rawDescOnce.Do(func() {
		file_proto_rithmic_rithmic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rithmic_rithmic_proto_rawDesc), len(file_proto_rithmic_rithmic_proto_rawDesc)))
	})
	return file_proto_rithmic_rithmic_proto_rawDescData
}

var file_proto_rithmic_rithmic_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_rithmic_rithmic_proto_goTypes = []any{
	(*DepthRequest)(nil), // 0: rithmic.DepthRequest
	(*PriceLevel)(nil),   // 1: rithmic.PriceLevel
	(*DepthUpdate)(nil),  // 2: rithmic.DepthUpdate
}
var file_proto_rithmic_rithmic_proto_depIdxs = []int32{
	1, // 0: rithmic.DepthUpdate.bids:type_name -> rithmic.PriceLevel
	1, // 1: rithmic.DepthUpdate.asks:type_name -> rithmic.PriceLevel
	0, // 2: rithmic.RithmicSidecar.SubscribeDepth:input_type -> rithmic.DepthRequest
	2, // 3: rithmic.RithmicSidecar.SubscribeDepth:output_type -> rithmic.DepthUpdate
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_rithmic_rithmic_proto_init() }
func file_proto_rithmic_rithmic_proto_init() {
	if File_proto_rithmic_rithmic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rithmic_rithmic_proto_rawDesc), len(file_proto_rithmic_rithmic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rithmic_rithmic_proto_goTypes,
		DependencyIndexes: file_proto_rithmic_rithmic_proto_depIdxs,
		MessageInfos:      file_proto_rithmic_rithmic_proto_msgTypes,
	}.Build()
	File_proto_rithmic_rithmic_proto = out.File
	file_proto_rithmic_rithmic_proto_goTypes = nil
	file_proto_rithmic_rithmic_proto_depIdxs = nil
}
