// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/rithmic/rithmic.proto

package rithmic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RithmicSidecar_SubscribeDepth_FullMethodName = "/rithmic.RithmicSidecar/SubscribeDepth"
)

// RithmicSidecarClient is the client API for RithmicSidecar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RithmicSidecarClient interface {
	SubscribeDepth(ctx context.Context, in *DepthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DepthUpdate], error)
}

type rithmicSidecarClient struct {
	cc grpc.ClientConnInterface
}

func NewRithmicSidecarClient(cc grpc.ClientConnInterface) RithmicSidecarClient {
	return &rithmicSidecarClient{cc}
}

func (c *rithmicSidecarClient) SubscribeDepth(ctx context.Context, in *DepthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DepthUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RithmicSidecar_ServiceDesc.Streams[0], RithmicSidecar_SubscribeDepth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DepthRequest, DepthUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RithmicSidecar_SubscribeDepthClient = grpc.ServerStreamingClient[DepthUpdate]

// RithmicSidecarServer is the server API for RithmicSidecar service.
// All implementations must embed UnimplementedRithmicSidecarServer
// for forward compatibility.
type RithmicSidecarServer interface {
	SubscribeDepth(*DepthRequest, grpc.ServerStreamingServer[DepthUpdate]) error
	mustEmbedUnimplementedRithmicSidecarServer()
}

// UnimplementedRithmicSidecarServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRithmicSidecarServer struct{}

func (UnimplementedRithmicSidecarServer) SubscribeDepth(*DepthRequest, grpc.ServerStreamingServer[DepthUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeDepth not implemented")
}
func (UnimplementedRithmicSidecarServer) mustEmbedUnimplementedRithmicSidecarServer() {}
func (UnimplementedRithmicSidecarServer) testEmbeddedByValue()                        {}

// UnsafeRithmicSidecarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RithmicSidecarServer will
// result in compilation errors.
type UnsafeRithmicSidecarServer interface {
	mustEmbedUnimplementedRithmicSidecarServer()
}

func RegisterRithmicSidecarServer(s grpc.ServiceRegistrar, srv RithmicSidecarServer) {
	// If the following call panics, it indicates UnimplementedRithmicSidecarServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RithmicSidecar_ServiceDesc, srv)
}

func _RithmicSidecar_SubscribeDepth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DepthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RithmicSidecarServer).SubscribeDepth(m, &grpc.GenericServerStream[DepthRequest, DepthUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RithmicSidecar_SubscribeDepthServer = grpc.ServerStreamingServer[DepthUpdate]

// RithmicSidecar_ServiceDesc is the grpc.ServiceDesc for RithmicSidecar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RithmicSidecar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rithmic.RithmicSidecar",
	HandlerType: (*RithmicSidecarServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeDepth",
			Handler:       _RithmicSidecar_SubscribeDepth_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/rithmic/rithmic.proto",
}
